name: Auto Fetch JSON and Commit

on:
  schedule:
    - cron: "*/2 * * * *"   # every 7 minutes
  workflow_dispatch:        # manual trigger

jobs:
  auto-fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # enables pushing

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run fetch script
        run: python fetch.py

      - name: Force commit always
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -m "Auto update $(date -u)" --allow-empty
          git push
