name: Auto Fetch JSON

on:
  schedule:
    - cron: "*/2 * * * *"   # Automatically every 5 minutes

jobs:
  auto-fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed to push commits

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run fetch script
        run: python fetch.py

      - name: Force commit always
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          
          git add .
          git commit -m "Auto update $(date -u)" --allow-empty
          git push
