name: Auto Commit JSON

on:
  schedule:
    - cron: "*/2 * * * *"  # Every 5 mins

jobs:
  commit-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch and update JSON
        run: |
          curl -s https://database.gformsnap.xyz/read?token=qazwsxedcrfv -o data.json

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated update data.json"
          file_pattern: data.json
